name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Create venv
        run: |
          uv sync --compile-bytecode

      - name: Run linter
        run: |
          source .venv/bin/activate
          make lint

      - name: Run tests
        run: |
          source .venv/bin/activate
          make test
